### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by Anand8317** [microhass/my-things-catalog#41]
Link to the project: [Kanban board](https://github.com/microhass/my-things-catalog/projects/1)

No of people in the project - 3

Team member 1: hassanShakur
Team member 2: Innocent259
Team member 3: Anand8317

**Comment by Shedrack-Sunday** [comment]
Hello @Anand8317 @Innocent259 and @hassanShakur          👋 

# CHANGES REQUIRED ♻️

Impressive work on the project so far👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Nice work with the Kanban features ✔️
- Good work with card descriptions ✔️ 
    

# Required Changes  🌵  

- [ ] I noticed from the card that the allocated points are not divided evenly. @Anand8317 has 28 points, @Innocent259 has 19.5 and @hassanShakur has 28. You can see the difference with @Innocent259 is almost 9 points. Kindly make sure the points are <=5 between the team members 👍 


_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Anand8317** [comment]
Thank you. Points are even now.

**Comment by Shedrack-Sunday** [comment]
Hello Team @Anand8317 @Innocent259 @hassanShakur . 

I mistakenly approved your project on the Dashboard instead of asking for changes. You'll get this corrected shortly. Please look forward to your dashboard, so you can submit the changes and get approved. 

My sincere apologies

**Comment by enniopo** [comment]
@Anand8317 @Innocent259 @hassanShakur Your dashboard has been updated. You can now request another code review request. Thank you

**Comment by hassanShakur** [comment]
Got it. Thanks @enniopo .
